export const ProjectCount = [
    // { value: "11", label: "Project Completed" },
];

export const PROJECTS = [
    {
        name: 'Sakoo.id',
        description: 'Sakoo (Satu Toko Online) merupakan salah satu dari 17 startup binaan Telkom yang memberikan solusi pengelolaan stok dan integrasi kanal penjualan bagi para pemilik bisnis. Sakoo adalah aplikasi web yang mengintegrasikan value chain penjualan ke dalam sistem pengelolaan stok yang dapat membantu pemilik bisnis meningkatkan efektivitas dan efisiensi dalam berjualan.',
        image: '/assets/projects/sakoo.webp',
        link: '',
        tags: [''],
    },
    {
        name: 'indbizPay',
        description: '​indibizPay adalah aplikasi transaksi bisnis digital yang dikembangkan oleh PT Telkom Indonesia. Aplikasi ini dirancang untuk membantu pelaku usaha, khususnya UMKM, dalam mengelola transaksi secara digital melalui fitur-fitur seperti pembayaran QRIS, penjualan pulsa dan tagihan (PPOB), serta pencatatan transaksi dengan sistem kasir digital.',
        image: '/assets/projects/indibizpay.png',
        link: '',
        tags: [''],
    },
    {
        name: 'BTPKLW',
        description: 'BTPKLW adalah singkatan dari Bantuan Tunai untuk Pedagang Kaki Lima dan Warung, yaitu program bantuan sosial tunai dari pemerintah Indonesia yang ditujukan kepada',
        image: '/assets/projects/btpklw.png',
        link: '',
        tags: [''],
    },
    {
        name: 'Bantujual.id',
        description: 'Bantujual.id adalah sebuah platform digital yang bertujuan untuk membantu pelaku usaha mikro, kecil, dan menengah (UMKM) dalam memasarkan produk mereka secara online. Platform ini menyediakan layanan untuk memfasilitasi penjualan melalui siaran langsung (live streaming), memungkinkan UMKM untuk menjangkau konsumen secara lebih luas tanpa harus memiliki tempat fisik untuk berjualan.',
        image: '/assets/projects/bantujual.png',
        link: '',
        tags: [''],
    },
    {
        name: 'DNM Mobile Office',
        description: 'Is an dashboard online for manage shopping application for K-Link customers and members and makes it easy for members to buy all K-Link products.',
        image: '/assets/projects/dnm-office.png',
        link: 'https://office.dnmmobile.com/',
        tags: [''],
    },
    {
        name: 'Openapi Docs PaDi UMKM',
        description: 'API PaDi UMKM merupakan layanan integrasi dengan platform pencarian produk B2B Commerce Marketplace PaDi UMKM. Memungkinkan pihak ketiga mengakses dan menggunakan berbagai macam fungsionalitas PaDi UMKM.',
        image: '/assets/projects/openapi-padi.png',
        link: 'https://openapi-docs.padiumkm.id/',
        tags: [''],
    },
    {
        name: 'DNM Mobile',
        description: 'Is an online shopping application for K-Link customers and members and makes it easy for members to buy all K-Link products.',
        image: '/assets/projects/dnm-mobile.png',
        link: 'https://dnmmobile.com/',
        tags: [''],
    },
    {
        name: 'Solution center PaDi UMKM',
        description: 'Solution Center PaDi UMKM adalah sebuah inisiatif atau platform yang disediakan oleh PaDi UMKM (Pasar Digital untuk Usaha Mikro, Kecil, dan Menengah) untuk membantu UMKM dalam mengatasi berbagai tantangan yang mereka hadapi, terutama dalam hal digitalisasi, pemasaran, dan akses ke pasar BUMN.',
        image: '/assets/projects/solution-padi.png',
        link: 'https://solutions.padiumkm.id/',
        tags: [''],
    },
    {
        name: 'Legal-Ize',
        description: 'Legal-Ize adalah platform yang menyediakan layanan hukum secara online, memungkinkan pengguna untuk mengakses berbagai dokumen hukum dan mendapatkan bantuan hukum dengan mudah dan cepat.',
        image: '/assets/projects/legal-ize.png',
        link: 'https://legal-ize.com/',
        tags: [''],
    },
    {
        name: 'ERM',
        description: 'Built an internal ERM system for PT Antara ETP to track, assess, and report business risks. Key features include risk/process inventorization, event reporting, KPI tracking, and BUMN-compliant workflows integrated with legal tools.',
        image: '/assets/projects/erm.png',
        link: '',
        tags: [''],
    },
    {
        name: 'Video Stitch Generator',
        description: '',
        image: '/assets/projects/mvg-staging.png',
        link: 'https://stitcher.frnd.io/',
        tags: [''],
    },
    {
        name: 'BRI Future Investment',
        description: 'BRIFINE adalah program pensiun dari DPLK BRI yang memudahkan Anda merencanakan masa depan lewat iuran rutin dan pilihan investasi fleksibel. Cocok untuk merencanakan dana pensiun pribadi sejak dini dengan cara praktis dan terpercaya.',
        image: '/assets/projects/brifine.png',
        link: '',
        tags: [''],
    },
    {
        name: 'Akademi Inspiradzi',
        description: 'Akademi Inspiradzi merupakan platform pembelajaran digital dari K-Link Nusantara yang menyediakan informasi seputar perusahaan serta berbagai materi bisnis dalam bentuk e-book, video, dan podcast.',
        image: '/assets/projects/akademiinspiradzi.png',
        link: 'https://akademiinspiradzi.com/',
        tags: [''],
    },
]