export const SKILLS = [
    "Vue.js",
    "React.js",
    "Nuxt.js",
    "Next.js",
    "TypeScript",
    "JavaScript",
    "Vuex",
    "React Native",
    "Flutter",
    "SCSS",
    "Cascading Style Sheets (CSS)",
    "Tailwind CSS",
    "REST APIs",
    "Google Maps API",
    "YouTube API",
    "Firebase",
    "Axios",
    "Zustand",
    "Redux",
    "Git",
    "GitHub",
    "GitLab",
    "Bitbucket",
    "Front-end Development",
    "Web Development",
    "Responsive Web Design",
    "Communication",
    "Team Coordination",
]; 